apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidstatfrontend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: sidstatfrontend
  template:
    metadata:
      labels:
        app: sidstatfrontend
    spec:
      containers:
      - name: sidstatfrontend
        image: izzkhair/sid_stat_frontend
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: sidstatfrontend
spec:
  type: LoadBalancer
  selector:
    app: sidstatfrontend
  ports:
  - port: 80
    targetPort: 3000
