FROM node:13.12.0-alpine
RUN --mount=type=secret,id=API_KEY \
  export API_PASSWORD=$(cat /run/secrets/API_PASSWORD) 
COPY package.json ./
COPY package-lock.json ./
RUN npm install
COPY . ./
CMD npm start