FROM node:13.12.0-alpine
COPY package.json ./
COPY package-lock.json ./
RUN npm install
COPY . ./
RUN --mount=type=bind,target=. \
  --mount=type=secret,id=API_KEY \
  API_KEY=$(cat /run/secrets/API_KEY) npm start