name: Backend CD

on:
  push:
    branches:
      - 'main'
    paths:
      - 'backend/**'


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Check out code
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: backend
          file: backend/dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/sid_stat_backend:latest